# Generated by Django 4.1.6 on 2023-04-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsmodel',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='ex : +91...'),
        ),
    ]
