# Generated by Django 4.1.6 on 2023-04-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_applicantsmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsmodel',
            name='contact',
            field=models.CharField(help_text='ex:+91...', max_length=100),
        ),
    ]
